# Generated by Django 6.1.1 on 2026-09-25 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=100, unique=True)),
                ('riot_id', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=50, unique=True)),
                ('champion', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=20)),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('win', models.BooleanField()),
                ('vision_score', models.IntegerField()),
                ('gold_earned', models.IntegerField()),
                ('damage_dealt', models.IntegerField()),
                ('game_duration', models.IntegerField()),
                ('game_date', models.DateTimeField()),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.summoner')),
            ],
        ),
    ]
